CREATE TABLE raw_iqvia.fact_category_ds_gc (
		period_group_cd STRING OPTIONS(description="Chave Grupo de Período FK"),
		market_ds_cd STRING OPTIONS(description="Chave Mercado FK"),
		otlt_rds_id STRING OPTIONS(description="Chave de Negócio PDV FK"),
		products_group_ds_cd STRING OPTIONS(description="Código de Negócio Grupo de Produtos FK"),
		fcc_rds_id STRING OPTIONS(description="ID FCC RDS"),
		category_nbr_units_qty STRING OPTIONS(description="Unidades"),
		category_nbr_units_dsg_qty STRING OPTIONS(description="Unidades Designadas"),
		category_nbr_list_price_lcurr_amt STRING OPTIONS(description="Valor Preço de Lista Moeda Local"),
		category_nbr_ppp_lcurr_amt STRING OPTIONS(description="Valor PPP Moeda Local"),
		category_nbr_consmpn_lcurr_amt STRING OPTIONS(description="Valor Consumo Moeda Local"),
		category_nbr_custom_price_lcurr_amt STRING OPTIONS(description="Valor Preço Personalizado Moeda Local"),
		category_nbr_private_price_lcurr_amt STRING OPTIONS(description="Valor Preço Privado Moeda Local"),
		category_nbr_non_retail_price_lcurr_amt STRING OPTIONS(description="Valor Preço Não Varejo Moeda Local"),
		category_nbr_pmc_price_lcurr_amt STRING OPTIONS(description="Valor Preço PMC Moeda Local"),
		category_nbr_ppp_price_st_otlt_type_lcurr_amt STRING OPTIONS(description="Valor Preço PPP por Tipo de PDV Moeda Local"),
		category_nbr_consmpn_price_st_otlt_type_lcurr_amt STRING OPTIONS(description="Valor Preço Consumo por Tipo de PDV Moeda Local"),
		category_nbr_ppp_consmpn_price_lcurr_amt STRING OPTIONS(description="Valor Preço PPP Consumo Moeda Local"),
		category_nbr_list_price_usd_amt STRING OPTIONS(description="Valor Preço de Lista Dólar Americano"),
		category_nbr_ppp_usd_amt STRING OPTIONS(description="Valor PPP Dólar Americano"),
		category_nbr_consmpn_usd_amt STRING OPTIONS(description="Valor Consumo Dólar Americano"),
		category_nbr_custom_price_usd_amt STRING OPTIONS(description="Valor Preço Personalizado Dólar Americano"),
		category_nbr_private_price_usd_amt STRING OPTIONS(description="Valor Preço Privado Dólar Americano"),
		category_nbr_non_retail_price_usd_amt STRING OPTIONS(description="Valor Preço Não Varejo Dólar Americano"),
		category_nbr_pmc_price_usd_amt STRING OPTIONS(description="Valor Preço PMC Dólar Americano"),
		category_nbr_ppp_price_st_otlt_type_usd_amt STRING OPTIONS(description="Valor Preço PPP por Tipo de PDV Dólar Americano"),
		category_nbr_consmpn_price_st_otlt_type_usd_amt STRING OPTIONS(description="Valor Preço Consumo por Tipo de PDV Dólar Americano"),
		category_nbr_ppp_consmpn_price_usd_amt STRING OPTIONS(description="Valor Preço PPP Consumo Dólar Americano"),
		category_nbr_units_qty_fct STRING OPTIONS(description="Fator Unidades"),
		category_nbr_units_qty_alt_fct STRING OPTIONS(description="Fator Unidades Alternativas"),
		category_nbr_units_dsg_qty_fct STRING OPTIONS(description="Fator Unidades Designadas"),
		category_nbr_list_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço de Lista Moeda Local"),
		category_nbr_ppp_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP Moeda Local"),
		category_nbr_consmpn_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Consumo Moeda Local"),
		category_nbr_private_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço Privado Moeda Local"),
		category_nbr_non_retail_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço Não Varejo Moeda Local"),
		category_nbr_pmc_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço PMC Moeda Local"),
		category_nbr_ppp_price_st_otlt_type_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP por Tipo de PDV Moeda Local"),
		category_nbr_consmpn_price_st_otlt_type_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço Consumo por Tipo de PDV Moeda Local"),
		category_nbr_ppp_consmpn_price_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP Consumo Moeda Local"),
		category_nbr_consmpn_weekly_lcurr_amt_fct STRING OPTIONS(description="Fator Valor Consumo Semanal Moeda Local"),
		category_nbr_list_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço de Lista Dólar Americano"),
		category_nbr_ppp_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP Dólar Americano"),
		category_nbr_consmpn_usd_amt_fct STRING OPTIONS(description="Fator Valor Consumo Dólar Americano"),
		category_nbr_pmc_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço PMC Dólar Americano"),
		category_nbr_ppp_price_st_otlt_type_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP por Tipo de PDV Dólar Americano"),
		category_nbr_consmpn_price_st_otlt_type_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço Consumo por Tipo de PDV Dólar Americano"),
		category_nbr_ppp_consmpn_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço PPP Consumo Dólar Americano"),
		category_nbr_private_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço Privado Dólar Americano"),
		category_nbr_non_retail_price_usd_amt_fct STRING OPTIONS(description="Fator Valor Preço Não Varejo Dólar Americano"),
		category_nbr_consmpn_weekly_usd_amt_fct STRING OPTIONS(description="Fator Valor Consumo Semanal Dólar Americano"),
		dt_hr_processamento TIMESTAMP OPTIONS(description="Data/Hora Processamento")
)
CLUSTER BY market_ds_cd, otlt_rds_id, products_group_ds_cd, fcc_rds_id
OPTIONS(
description="Tabela que contém dados de vendas agregados por categoria, incluindo unidades e diversos tipos de preços em moeda local e dólar."
)
;